import { defineConfig } from "vitepress"

export default defineConfig({
  title: "terminfo.dev",
  description: "Can your terminal do that? Feature support tables for terminal emulators.",
  cleanUrls: true,
  head: [["link", { rel: "icon", href: "/favicon.svg" }]],

  themeConfig: {
    nav: [
      { text: "Matrix", link: "/" },
      { text: "About", link: "/about" },
      { text: "termless.dev", link: "https://termless.dev" },
    ],

    socialLinks: [{ icon: "github", link: "https://github.com/beorn/termless" }],

    footer: {
      message: "Powered by termless — headless terminal testing",
      copyright: "Data generated by automated census probes",
    },
  },
})
